attribute vec3 randomPosition;
attribute vec3 targetPosition;
attribute vec3 sampleColor;
uniform float uProgress;
uniform float uTime;
uniform float uDpr;
uniform float uPointSize;
uniform vec4 uImageRect;
varying float vAlpha;
varying vec3 vColor;
varying float vEnergy;
void main() {
  vec2 targetUV = uImageRect.xy + targetPosition.xy * uImageRect.zw;
  vec2 target = vec2(targetUV.x * 2.0 - 1.0, 1.0 - targetUV.y * 2.0);
  float delay = randomPosition.z * .13 + targetPosition.y * .035;
  float progress = smoothstep(0.0, 1.0, clamp((uProgress - delay) / .84, 0.0, 1.0));
  float inverse = 1.0 - progress;
  float side = sign(randomPosition.x);
  vec2 control = mix(randomPosition.xy, target, .5);
  control += vec2(-side * (.2 + randomPosition.z * .22), (randomPosition.z - .5) * .62);
  vec2 p = inverse * inverse * randomPosition.xy + 2.0 * inverse * progress * control + progress * progress * target;
  vec2 tangent = normalize(vec2(-(target.y - control.y), target.x - control.x) + vec2(.001));
  float curl = sin(progress * 3.14159) * (.055 + randomPosition.z * .07);
  p += tangent * curl * sin(uTime * 2.4 + randomPosition.z * 24.0 + target.y * 5.0);
  p += (randomPosition.z - .5) * vec2(.07, .035) * inverse;
  float lockPulse = exp(-pow((uTime - 1.82) * 6.0, 2.0));
  gl_Position = vec4(p, (randomPosition.z - .5) * .12 * inverse, 1.0);
  gl_PointSize = uPointSize * uDpr * (.58 + randomPosition.z * .35 + lockPulse * .42);
  vAlpha = .56 + targetPosition.z * .36;
  vEnergy = sin(progress * 3.14159) * .42 + lockPulse;
  vec3 noirBlue = mix(vec3(.24, .38, .68), vec3(.68, .55, .9), randomPosition.z);
  float sourceMix = smoothstep(.72, 1.0, progress);
  vColor = mix(noirBlue, sampleColor * 1.28 + vec3(.035), sourceMix);
}
