import { readFileSync, writeFileSync } from "node:fs";
const files = {
  planeVertex: "shaders/plane.vert",
  noise: "shaders/noise.glsl",
  utils: "shaders/utils.glsl",
  lensFragment: "HairLens/hairLens.frag",
  transitionFragment: "HairTransition/transition.frag",
  hairRibbonVertex: "HairLoom/hairRibbon.vert",
  hairRibbonFragment: "HairLoom/hairRibbon.frag",
  cinematicHairVertex: "CinematicHairJourney/cinematicHair.vert",
  cinematicHairFragment: "CinematicHairJourney/cinematicHair.frag",
  hairJourneyParticleVertex: "CinematicHairJourney/hairJourneyParticles.vert",
  hairJourneyParticleFragment: "CinematicHairJourney/hairJourneyParticles.frag",
  hairJourneyThreadsVertex: "CinematicHairJourney/hairJourneyThreads.vert",
  hairJourneyThreadsFragment: "CinematicHairJourney/hairJourneyThreads.frag",
  particleVertex: "ParticleHead/particleHead.vert",
  particleFragment: "ParticleHead/particleHead.frag",
};
const output = Object.entries(files)
  .map(
    ([name, file]) =>
      `export const ${name} = ${JSON.stringify(readFileSync(new URL("../src/three/" + file, import.meta.url), "utf8"))};`,
  )
  .join("\n");
writeFileSync(
  new URL("../src/three/shaders.generated.ts", import.meta.url),
  "// Generated by scripts/build-shaders.mjs. Edit the .glsl/.vert/.frag sources.\n" +
    output +
    "\n",
);
