import { chromium } from "@playwright/test";
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } });
page.on("pageerror", (error) => console.log("PAGE ERROR", error.message));
page.on("console", (message) => { if (["error", "warning"].includes(message.type())) console.log(message.type(), message.text()); });
await page.addInitScript(() => sessionStorage.setItem("noir-opening-portrait-v4", "1"));
await page.goto("http://localhost:3000/", { waitUntil: "domcontentloaded" });
const entry = page.getByTestId("color-reveal-entry");
await entry.scrollIntoViewIfNeeded();
await page.waitForFunction(() => (document.querySelector('[data-testid="color-reveal-entry"] img'))?.complete);
await entry.screenshot({ path: "docs/screenshots/color-reveal-entry.png" });
console.log("TOP", { content: (await entry.innerText()).slice(0, 90), canvases: await entry.locator("canvas").count(), overlay: await page.locator("[data-nextjs-dialog]").count() });
await entry.getByRole("link", { name: "ENTER THE COLOR EXPERIENCE" }).click();
await page.waitForURL("**/color-reveal");
const section = page.getByTestId("hair-color-particle-reveal");
await section.scrollIntoViewIfNeeded();
await page.waitForTimeout(5000);
console.log("ENGINE", await section.getAttribute("data-engine"));
console.log("CANVAS", await section.locator("canvas").evaluateAll((nodes) => nodes.map((n) => ({ ...n.dataset }))));
await section.getByRole("radio", { name: "SILVER", exact: true }).check();
await page.waitForTimeout(1000);
await section.screenshot({ path: "docs/screenshots/color-reveal-desktop-motion.png" });
console.log("MOTION", await section.locator("canvas").evaluateAll((nodes) => nodes.map((n) => ({ ...n.dataset }))));
await page.waitForTimeout(3000);
await section.screenshot({ path: "docs/screenshots/color-reveal-desktop.png" });
await browser.close();
